### PR TITLE
feat: open the schedule page

### PR DESCRIPTION
**Pull request by Ritabear**
## Description
 open the schedule page

## Expected behavior
can watch the schedule page.

## Related Issue
#530

### CODE REVIEW

**Comment by SivanYeh** [comment]
LGTM!

**Comment by tyuchx** [comment]
LGTM

**Review by tyuchx — APPROVED** [review]

**Comment by tyuchx** [comment]
@Ritabear 需要再麻煩修一下衝突

**Review by SivanYeh — APPROVED** [review]
LGTM!

**Pull request merged**
