### PR TITLE
feat: modify banner and layout for Ticket page

### PR DESCRIPTION
**Pull request by SivanYeh**
## Types of changes

* **Bugfix**

## Description

modify layout to fit the design spec
image

## Related Issue

#267

### CODE REVIEW

**Comment by mattwang44** [comment]
@SivanYeh 這個 PR 改動到其他已經被 merged 的 PR 做的 code change，請記得 rebase 一下並檢查是不是只留下你想要的改動

**Comment by SivanYeh** [comment]
@mattwang44 謝謝提醒! 我明後天檢查一下

**Comment by SivanYeh** [comment]
@mattwang44 unsolved: title core-h1 need to break too

**Review by mattwang44 — APPROVED** [review]
- organized commit history
- rebased
- added a commit for title line break handling

**Pull request merged**
