### PR TITLE
feat(proposal): change poster-session submit date UI

### PR DESCRIPTION
**Pull request by mhsiungw**
## Types of changes

* **Update UI**
Screenshot 2024-06-16 at 23 16 12

## DEMO

Screenshot 2024-06-16 at 23 11 42
Screenshot 2024-06-16 at 23 11 46

## Steps to Test This Pull Request
Go to the path /speaking/poster-session

### CODE REVIEW

**Comment by SivanYeh** [comment]
@mhsiungw AoE連結再更新完就沒問題了～
這是新的6/30連結：
https://www.timeanddate.com/worldclock/converter.html?iso=20240701T115900&p1=tz_aoe&p2=241&p3=1440

**Comment by SivanYeh** [comment]
(just some nice-to-have) btw PR, commits的寫法可以參考這一篇文章：
https://www.conventionalcommits.org/en/v1.0.0/

以這次PR為例可以這樣寫：
PR title:
feat(proposal): change poster-session submit date UI 

commit msg:
feat(proposal): update submit date in poster-session' s i18n

**Comment by mhsiungw** [comment]
> (just some nice-to-have) btw PR, commits的寫法可以參考這一篇文章： https://www.conventionalcommits.org/en/v1.0.0/
> 
> 以這次PR為例可以這樣寫： PR title: feat(proposal): change poster-session submit date UI
> 
> commit: feat(proposal): update submit date in poster-session' s i18n
> 
> 在PR介紹裡面除了Types of changes外, 可以新增簡短的測試方式： 例如：
> 
> ## Steps to Test This Pull Request
> Go to the path /speaking/poster-session

@SivanYeh 沒問題，已針對建議修改！

**Comment by SivanYeh** [comment]
LGTM!

**Review by SivanYeh — APPROVED** [review]

**Pull request merged**
