### PR TITLE
chore(env): adjust scripts for json-server

### PR DESCRIPTION
**Pull request by wanyewei**
## Types of changes

* **Other **

## Description

解決在windows環境下，run json-server 出現的錯誤
image

## Steps to Test This Pull Request
1. 在vscode的terminal執行npm run json-server
2. 在vscode的terminal內會顯示  Home  http://localhost:9876
3. 到瀏覽器上輸入 http://localhost:9876，成功跑出畫面。

## Expected behavior

image

### CODE REVIEW

**Comment by SivanYeh** [comment]
剛剛測試這些改動在我的本地端也是相容的(MacOS M1)->除了[package-lock.json](https://github.com/pycontw/pycontw-frontend/pull/538/files/6508841a5eb32108ba13ecdcf32e0483f4db8234#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519) 我有疑問, 其餘我覺得可以併到codebase了.
 @mattwang44 @josix @baby230211 可以協助看看 .eslintrc.js與package.json上的變更是安全的嗎?

**Comment by mattwang44** [comment]
yes, these changes look safe to me
- [prettier's end-of-line rule](https://prettier.io/docs/en/options.html#end-of-line)
- After `nvm use 14.21.3 && npm ci`, both `npm run json-server` and `npm run lint` work fine on my machine (M1 Sonoma).

**Comment by tyuchx** [comment]
LGTM

After nvm use 16.20.2 && npm ci, both npm run json-server and npm run lint work fine on my machine (M3 Sonoma 14.4).

**Review by SivanYeh — APPROVED** [review]
LGTM!

**Pull request merged**
