### PR TITLE
feat(schedule's room): expand rooms of the schedule and make it scrollable

### PR DESCRIPTION
**Pull request by lingin1230**
## Types of changes

* **New feature**

## Description

Expand the room of the schedule and make it scrollable,<br/>
but the room name for the two days is temporarily hard code in front-end.<br/><br/>
ps. will try to center the text of the event content in all rooms later.
## Steps to Test This Pull Request

Please run dev and visit site /conference/schedule

## Expected behavior

schedule-scroll

### CODE REVIEW

**Review by mattwang44 — CHANGES_REQUESTED** [review]
~~有幾個 warning 要記得修一下~~
我有先把它修掉了

image
image

**Comment by mattwang44** [comment]
這版會先佈上線，其他 feature request 就另外開 PR 改就好

**Review by mattwang44 — APPROVED** [review]
LGTM

**Comment by lingin1230** [comment]
@mattwang44 非常感謝！！

**Pull request merged**
