### PR TITLE
feat(speech): toggle talks and tutorials pages

### PR DESCRIPTION
**Pull request by SivanYeh**
## Types of changes

* **New feature**

## Description

Switch on 2024 Tutorials(專業課程) and Talks(一般演講) pages

## Steps to Test This Pull Request
1. Go to path/2024/zh-hant/conference/talks 
2. Go to path/2024/zh-hant/conference/tutorials 
3. Check if they can be entered from navigation bar "Conference/Talks" and "Conference/Tutorials"

## Expected behavior

image

## Related Issue

#529 
#528

### CODE REVIEW

**Comment by SivanYeh** [comment]
@mattwang44 @josix 本地端點擊任一演講區塊找不到頁面。我漏開了什麼嗎？
image

GET /speeches/?event_type=talk,sponsored 304 9.700 ms - -
GET /speeches/?event_type=talk&id=3&singular=1 304 4.415 ms - -
GET /speeches/?event_type=category&id=SEC&singular=1 404 3.363 ms - 2

**Comment by mattwang44** [comment]
有跑 npm run json-server 嗎？
這個頁面上的資料是透過 API 拿到的（local dev 現在應該還是？）

**Comment by SivanYeh** [comment]
有跑npm run json-server~
local dev有輸入兩筆假資料. 不過按照顯示結果應該是直接去API抓

**Comment by mattwang44** [comment]
@SivanYeh please test it out with this patch
https://github.com/pycontw/pycontw-frontend/pull/551

**Comment by SivanYeh** [comment]
@tomatoprinx The previous is fixed by Matt. Please check again on your local~

**Review by tomatoprinx — APPROVED** [review]

**Pull request merged**
