### PR TITLE
[fix] fix broken image on the landing title

### PR DESCRIPTION
**Pull request by erik1110**
* **Bugfix**

## Description
 fix broken image on the landing title
- Before
image

- After
image

### CODE REVIEW

**Comment by josix** [comment]
@tim08094495757 I guess fixed min-height also could fix the issue #382, right?

**Review by tim08094495757 — COMMENTED** [review]
Thanks, @erik1110 and @josix.
Getting rid of vh or vw for min-height is a really good idea.
1. But to support 1920x1080 or more than this resolution, I suggest adding code like
    ```
    @media (min-width: 1600px) {
        .landing__title {
            min-height: 330px;
            min-width: 864px;
        }
    }
    ```
    and transforming it into a tailwind style if necessary.

2. Explanation (Can skip this part XD. I don't know how to explain it simply.)
    1. Definition
        - h: Screen height 
        - w: Screen width
        - real-img-size: Width x Height
        - real-img-bottom-pad: The distance of the red line under a real image
        image

    2. Assumption
        1. Only consider screen sizes in https://www.altamira.ai/blog/common-screen-sizes-for-responsive-web-design/
        2. Without considering all the effects of height by sth like toolbar
        
        =>
        
        - max-h: 1280px
        - max-w: 1920px
        - min-h: 601px
        - min-w: 360px

3. Validation (By a system of equations and inequalities)
    1. Original
        - background-position-y: 40px
        - real-img-size: 750 x 367
        - real-img-bottom-pad: 40px
        
        =>
        
        - h: 50vh
        - w: 100vw
        
        =>
        
        - x≥360
        - x≤768
        - y≥(367-40)x/750+40
        - y≤1280x0.5
        - y≥601x0.5
        
        => (x, y) = x, y/0.5 = w, h // Can test w, h by Chrome device toolbar.
        
        =>
        
        image
        
        - We can know points like (607, 305) is feasible, but (767, 305) is not infeasible. 
        - Points are infeasible in the triangle.
        
        => But I think it's fine to have infeasible points according to the assumption.

    2. Media Query (min-wdith: 768px)
        - background-position-y: 50px
        - real-img-size: 1276 x 447
        - real-img-bottom-pad: 35px
        
        =>
    
        - h: 280px
        - w: 45vw
        
        =>
        
        - x≥768x0.45,
        - x≤1920x0.45,
        - y≥(447-35)x/1276+50,
        - y=280,
        
        => (x, y) = x/0.45, h = w, h
        
        => 
        
        image
        
        - 1600px: We can know (712, 280) is feasible.  1582 (712/0.45) px is close to 1600px defined as '2xl' in tailwind.config.js.
        - 330px: 328.972 is close to 330.
        - 864px: (330-50)*1276/(447-35)>864.
        
        This is why the suggested code has 1660, 330, and 864 in it.

**Comment by yungshenglu** [comment]
@tim08094495757 數學大師

**Comment by tim08094495757** [comment]
> @tim08094495757 數學大師

不敢當。要解的Issue比想像中有挑戰性～

**Review by josix — APPROVED** [review]
LGTM! Thanks to @erik1110 and @tim08094495757

**Pull request merged**
